import random
import streamlit as st

films = {
    'Action': ["John Wick", "Mad Max Fury Road", "The Dark Knight", "Gladiator", "Extraction", "Nobody", "The Equalizer", "Mission Impossible", "Fast and Furious", "Avengers Endgame", "Captain America Winter Soldier", "Iron Man", "The Matrix", "Terminator 2", "Skyfall", "The Raid", "Rambo", "Die Hard", "Kingsman", "Edge of Tomorrow","Heat", "Casino Royale", "The Bourne Ultimatum", "V for Vendetta", "Kill Bill Vol. 1", "Kill Bill Vol. 2", "Top Gun: Maverick"],
    'Adventure': ["Indiana Jones", "Jumanji", "The Mummy", "Pirates of the Caribbean", "Journey to the Center of the Earth", "Uncharted", "The Jungle Book", "Life of Pi", "Avatar", "King Kong", "The Revenant", "The Lost City", "Around the World in 80 Days", "Dora and the Lost City", "Jungle Cruise", "The Secret Life of Walter Mitty","Into the Wild", "The Beach", "Everest", "The Way Back", "Kong: Skull Island", "The Maze Runner", "Prince of Persia: The Sands of Time"],
    'Romcoms': ["About Time", "The Big Sick", "Silver Linings Playbook", "13 Going on 30", "Shes the Man", "To All the Boys Ive Loved Before", "Definitely, Maybe","Crazy Rich Asians", "Notting Hill", "The Proposal", "10 Things I Hate About You", "Love Actually", "Friends with Benefits", "No Strings Attached", "The Holiday", "Pretty Woman", "Shes All That", "How to Lose a Guy in 10 Days", "Just Go With It", "Bridget Jones Diary", "Hitch", "Clueless","Titanic", "The Notebook", "Me Before You", "La La Land", "Pride and Prejudice", "Before Sunrise", "The Fault in Our Stars", "500 Days of Summer", "A Walk to Remember", "Love Simon", "Call Me By Your Name", "After", "The Vow", "Midnight Sun"],
    'Comedy': ["Mr Beans Holiday", "The Mask", "Dumb and Dumber", "Superbad", "Step Brothers", "White Chicks", "Scary Movie", "American Pie", "Rush Hour", "Johnny English", "Borat", "The Dictator", "Ted", "Central Intelligence", "Ride Along", "Grown Ups", "Home Alone", "Night at the Museum", "Game Night", "Were the Millers", "The Nice Guys", "Get Smart", "Johnny English Reborn", "Horrible Bosses", "The Internship"],
    'Horror': ["The Autopsy of Jane Doe", "The Invisible Man", "The Witch", "Midsommar", "Oculus", "Dont Breathe", "The Visit", "Us","The Conjuring", "Insidious", "Annabelle", "The Nun", "It", "A Quiet Place", "The Ring", "The Exorcist", "Sinister", "Hereditary", "The Babadook", "Paranormal Activity", "The Grudge", "Lights Out"],
    'Science Fiction': ["Annihilation", "Upgrade", "Looper", "Oblivion", "Sunshine", "Source Code", "Predestination", "Children of Men","Interstellar", "Inception", "The Matrix", "Avatar", "Dune", "Tenet", "Blade Runner 2049", "Ex Machina", "Arrival", "Gravity", "The Martian", "Edge of Tomorrow", "Ready Player One", "Tron Legacy"],
    'Romance': ["The Age of Adaline", "Safe Haven", "Dear John", "Endless Love", "The Lucky One", "If I Stay", "Remember Me","Titanic", "The Notebook", "Me Before You", "La La Land", "Pride and Prejudice", "Before Sunrise", "The Fault in Our Stars", "500 Days of Summer", "A Walk to Remember", "Love Simon", "Call Me By Your Name", "After", "The Vow", "Midnight Sun"],
    'Anime': ["Perfect Blue", "Paprika", "The Girl Who Leapt Through Time", "Tokyo Godfathers", "Wolf Children", "Promare", "Suzume", "Belle","Your Name", "Spirited Away", "Attack on Titan", "Demon Slayer Mugen Train", "Naruto Movies", "One Piece Film Red", "A Silent Voice", "Weathering With You", "Dragon Ball Super Broly", "Jujutsu Kaisen 0", "Tokyo Ghoul"],
    'Cartoons': ["Megamind", "Cloudy with a Chance of Meatballs", "The Croods", "Rio", "Bolt", "Brave", "Luca", "Turning Red","Toy Story", "Cars", "Finding Nemo", "Frozen", "Shrek", "Despicable Me", "Minions", "Kung Fu Panda", "The Incredibles", "Ratatouille", "Coco", "Inside Out", "Madagascar", "Ice Age"],
    'Documentary': ["The Rescue", "Icarus", "13th", "Wont You Be My Neighbor", "My Octopus Teacher", "The Cove", "Food Inc", "Exit Through the Gift Shop","The Social Dilemma", "Inside Job", "Our Planet", "Planet Earth", "Free Solo", "The Last Dance", "Seaspiracy", "Cowspiracy", "Making a Murderer", "Blackfish", "The Tinder Swindler"],
    'Drama': ["There Will Be Blood", "No Country for Old Men", "The Master", "Moonlight", "Drive", "The Florida Project", "Blue Valentine", "The Place Beyond the Pines","The Pursuit of Happyness", "Forrest Gump", "The Shawshank Redemption", "Joker", "Fight Club", "Green Book", "Whiplash", "Parasite", "The Pianist", "Room", "Marriage Story", "The Irishman", "Prisoners"],
    'Fantasy': ["The Green Knight", "Coraline", "The NeverEnding Story", "Willow", "Legend", "Inkheart", "The Imaginarium of Doctor Parnassus", "MirrorMask","Harry Potter", "The Lord of the Rings", "The Hobbit", "Fantastic Beasts", "The Chronicles of Narnia", "Percy Jackson", "Alice in Wonderland", "Maleficent", "Pans Labyrinth", "Stardust", "The Golden Compass", "Eragon"],
    'K-drama': ["Crash Landing on You", "Itaewon Class", "Goblin", "Descendants of the Sun", "Vincenzo", "The Glory", "Business Proposal", "True Beauty", "My Name", "All of Us Are Dead", "Sweet Home", "Hometown Cha-Cha-Cha", "Start-Up", "Hotel Del Luna", "Reply 1988", "Whats Wrong with Secretary Kim", "Flower of Evil", "Mouse", "Signal", "Healer"]
}

st.title("🎬 Find Your Next Movie 🎬")
genre = st.selectbox("Choose your favorite genre:", list(films.keys()))

if st.button("Give me a movie 🎬"):
    movie = random.choice(films[genre])
    st.success(f"Your movie is: {movie}")